backend:
  name: github
  repo: dutraneto/2022-blog
  base_url: https://2022-blog.vercel.app/
  auth_endpoint: api/auth/ # Essa rota vai ser muito importante mais para frente

media_folder: public/images
public_folder: images

publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: posts
    label: posts
    folder: posts # A pasta onde ficarão os posts
    create: true # Permite criar um post novo
    slug: '{{slug}}' # Estrutura do nome arquivo, exemplo: title.md
    fields: # Os campos do seu frontmatter
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD'
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - { label: 'Language', name: 'language', widget: 'string' }
      - { label: 'Post Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
